name: Build and Release EXE
on:
  push:
    paths:
      - 'VBoxTabs-Manager.py'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka
          pip install zstandard  # Required for Nuitka compression
      
      - name: Extract version from VBoxTabs-Manager.py
        id: get_version
        run: |
          $content = Get-Content VBoxTabs-Manager.py
          $versionLine = $content | Select-String -Pattern 'version_label\s*=\s*QLabel\("Version ([0-9.]+[a-zA-Z0-9_-]*)"'
          if ($versionLine) {
            $version = $versionLine.Matches[0].Groups[1].Value
            echo "Raw version detected: $version"
          } else {
            $version = "0.0"
            echo "No version found, using default: $version"
          }
          echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
      - name: Build with Nuitka
        run: |
          nuitka --assume-yes-for-downloads --standalone --follow-imports --enable-plugin=pyside6 --include-package=win32gui --include-package=win32process --include-package=win32con --include-package=win32api --include-package=qdarkstyle --static-libpython=no --company-name="Zalexanninev15" --product-name="VBoxTabs Manager" --file-version="${{ steps.get_version.outputs.version }}" --lto=yes --show-memory --show-progress --nofollow-import-to=tkinter --nofollow-import-to=PIL --nofollow-import-to=numpy --jobs=8 --windows-console-mode=disable --remove-output -o "VBoxTabs Manager.exe" VBoxTabs-Manager.py
      
      - name: Create ZIP archive
        run: |
          Rename-Item -Path "VBoxTabs-Manager.dist" -NewName "VBoxTabs Manager"
          Compress-Archive -Path "VBoxTabs Manager" -DestinationPath "VBoxTabs-Manager.zip"
      
      - name: Upload directory artifact
        uses: actions/upload-artifact@v4
        with:
          name: VBoxTabs-Manager
          path: VBoxTabs Manager/
      
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: VBoxTabs-Manager-ZIP
          path: VBoxTabs-Manager.zip
      
      - name: Get commit message
        id: get_commit_message
        run: |
          $commitMessage = git log -1 --pretty=%B
          $commitMessage = $commitMessage -replace "`n","\n" -replace "`r",""
          echo "message=$commitMessage" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Version ${{ steps.get_version.outputs.version }}
          body: |
            Automatic build for Version ${{ steps.get_version.outputs.version }}.
            
            ## Changes
            ${{ steps.get_commit_message.outputs.message }}
            
            See [README](https://github.com/Zalexanninev15/VBoxTabs-Manager#readme) for usage instructions.
          files: |
            VBoxTabs-Manager.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}